# Generated by Django 5.1.1 on 2024-11-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(default='all_image/2.jpg', upload_to='static/profile'),
        ),
    ]
