# Generated by Django 5.1.1 on 2024-12-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(blank=True, default='media/profile/user_default.jpg', upload_to='media/profile/'),
        ),
    ]
