# Generated by Django 5.1.1 on 2024-09-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='image',
            field=models.ImageField(default='all_image/2.jpg', upload_to='all_image/'),
        ),
        migrations.AddField(
            model_name='out',
            name='image',
            field=models.ImageField(default='all_image/2.jpg', upload_to='all_image/'),
        ),
    ]
