# Generated by Django 5.1.1 on 2024-11-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_income_image_out_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='image',
            field=models.ImageField(blank=True, default='all_image/2.jpg', upload_to='media/all_image/'),
        ),
        migrations.AlterField(
            model_name='income',
            name='time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
