# Generated by Django 5.1.1 on 2024-12-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_income_image_alter_income_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='out',
            name='image',
            field=models.ImageField(blank=True, default='all_image/2.jpg', upload_to='all_image/'),
        ),
        migrations.AlterField(
            model_name='out',
            name='time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
