# Generated by Django 5.1.1 on 2024-12-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_out_image_alter_out_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='out',
            name='Featured',
            field=models.BooleanField(default=False),
        ),
    ]
