# Generated by Django 5.1.1 on 2024-12-11 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_income_featured_out_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='out',
            old_name='Featured',
            new_name='featured',
        ),
    ]
