# Generated by Django 5.1.1 on 2024-12-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_rename_featured_out_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='image',
            field=models.ImageField(blank=True, default='media/all_image/2.jpg', upload_to='media/all_image/'),
        ),
        migrations.AlterField(
            model_name='out',
            name='image',
            field=models.ImageField(blank=True, default='media/all_image/2.jpg', upload_to='media/all_image/'),
        ),
    ]
